import { type NextPage } from "next";
import Head from "next/head";
import Hero from "~/components/home-page/Hero";
import Popular from "~/components/home-page/Popular";
import SearchSection from "~/components/home-page/SearchSection";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Popular />
      <SearchSection />
    </>
  );
};

export default Home;
