export const mockupData = {
  name: 'Chicken breast',
  id: 'someNiceId111',
  uid: 'userCreatorId111',
  imageUrl: '/plate-food.jpg',
  categories: ['Breakfast', 'Oats', 'Bananas'],
  time: 30,
  servingsDef: 2,
  ingredients: [
    {
      name: 'rice',
      quantity: 100,
      unit: 'g',
      quantitySecondary: 2,
      unitSecondary: 'v.s.',
    },
    { name: 'chicken2', quantity: 200, unit: 'vnt.' },
    { name: 'chicken chicken chicken', quantity: 200, unit: 'g' },
    { name: 'chicken3', quantity: 200, unit: 'g' },
    { name: 'chicken2 chicken2 chicken2', quantity: 200, unit: 'g' },
    { name: 'chicken2 chicken2 chicken4', quantity: 200, unit: 'g' },
    {
      name: 'chicken chicken chicken chicken chicken',
      quantity: 200,
      unit: 'g',
    },
    { name: 'chicken chicken', quantity: 200, unit: 'vnt.' },
  ],
  preparation: [
    'Cut ...',
    'Boil...',
    'Cook...',
    'Season...',
    'Mix...',
    'Pour...',
    'Eat...',
  ],
  notes: ['Instead of ... you can use ...'],
};
